# Generated by Django 6.0.4 on 2026-06-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('termogenicos', 'Termogênicos'), ('proteicos', 'Proteicos'), ('vitaminas', 'Vitaminas')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
