# Generated by Django 6.0.4 on 2026-06-09 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_produto_descricao_remove_produto_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
